### ISSUE TITLE
Separate window is opening up to download the video file

### ISSUE THREAD

**Issue by hanumantha03** [7Ds7/videojs-vjsdownload#3]
I am using **.mpd** file in the src attribute of the video.js player. I have used your plugin to download the **.mp4** video, but when I am clicking on the download button a separate tab is opening. Is it possible to trigger the download while being in the same tab? If yes, where should I make changes in the code?

![image](https://user-images.githubusercontent.com/32599055/52053789-5397a700-2580-11e9-8183-35dcb8b8f104.png)

Thanks in advance!!

**Comment by 7Ds7** [comment]
In short no.

You can although fork this repo if you want and use window.location.href instead of window open if you want to.

**Comment by hanumantha03** [comment]
I tried even that and it is also not helping....

**Comment by 7Ds7** [comment]
I updated the README with a demo https://github.com/7Ds7/videojs-vjsdownload/blob/master/README.md

If you wan't to change the way download is triggered you have to change it here in your own fork https://github.com/7Ds7/videojs-vjsdownload/blob/master/src/plugin.js#L33 and re-build the plugin

**Comment by hanumantha03** [comment]
is it possible to do like this:

@method handleClick
  */
  handleClick(player) 
  {
    
    var temp = player.src();
      player.src() = this.options_.downloadURL;
      window.location.href = player.src();
      player.src() = temp;
    // window.open(this.options_.downloadURL || p.currentSrc(), 'Download');
    //p.trigger('downloadvideo');
  }

from line 28 in vjsdownload.js. 
I just want to accesss the player's **src** property in handleClick event could you please tell me  how can I do that?

**Comment by 7Ds7** [comment]
There is no clean way to do so

Option 1 you had headers on the request
https://css-tricks.com/snippets/htaccess/force-files-to-download-not-open-in-browser/

Option 2 you add one anchor tag with the download attribute and simulate the click
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

Instead of src you can set a custom downloadURL and access trough this.options_.downloadURL

**Comment by drschwabe** [comment]
This click handler intercept does the trick (note the $j for jquery; change to $ if necessary or whatever your jquery var name ) 

```
document.body.addEventListener('click', e => {
  if (e.target.matches('.vjs-download')) {
    e.preventDefault()
    e.stopPropagation()
    const link = document.createElement('a')
    const dlPath = $j(e.target).closest('.video-js').find('video').attr('src')      
    link.href = dlPath 
    link.download = dlPath 
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)    
    return false 
  }
}, { capture: true })  
```
